# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d32e60f894f771766e32e7114cffe5e562d31b3451e978766d83266842b5829004761fdf44a94c493bd1c25f25526fa3a69593cdf476d1c24286e2f6cf11889

test:
  secret_key_base: 96b0efca192451092853401b379b40dd53240ed6c8d516d34a826d9a119397bad1a87bcda1b03ac2d2a376cb93268f26beaae651673c2180d63f4df92452bee5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
